# ------------------------------------------------------------------------------
# i3status-rust configuration file.
# see "man i3status-rs" for documentation.
# https://github.com/greshake/i3status-rust
#
# For a list of available blocks, see:
# https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html
# ------------------------------------------------------------------------------

[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "music"
format = " $icon $artist - $title $prev $play $next "

[[block]]
block = "sound"

[[block]]
block = "cpu"
format = " $icon $utilization "

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
warning_mem = 70
critical_mem = 90
warning_swap = 20
critical_swap = 90

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "

[[block]]
block = "net"
format = " $icon $device "

[[block]]
block = "backlight"
device = "intel_backlight"
missing_format = ""

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "$variant"

[[block]]
block = "notify"
format = " $icon {$paused{Off}|On} "

[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"
missing_format = ""
empty_format = ""

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 5
